--DATABASES
IF DB_ID('SportsDataDb') IS NULL
BEGIN
    CREATE DATABASE SportsDataDb;
END
GO

USE SportsDataDb;
GO
--TABLES
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Team' AND xtype='U')
BEGIN
    CREATE TABLE dbo.Team
    (
        Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        [Name] NVARCHAR(255) NOT NULL,
        CityId UNIQUEIDENTIFIER NOT NULL,
        CountryId UNIQUEIDENTIFIER NOT NULL,
        StadiumId UNIQUEIDENTIFIER NOT NULL,
        LeagueId UNIQUEIDENTIFIER NOT NULL,
        LogoUrl NVARCHAR(1024) NOT NULL,
        ShortName NVARCHAR(100) NOT NULL
    );
END
